Repository schramm-famm/patches, pull requests merged in 2020-04, with the labels that each got.

#28 Add SQL setup code
  Dockerfile
  Makefile
  app/server.go
  dbSchema.sql
  models/db.go
  models/patch.go
Labels: bug, enhancement

#29 Add Terraform config for patches
  Makefile
  terraform/main.tf
  terraform/modules/patches/main.tf
  terraform/modules/patches/output.tf
  terraform/modules/patches/variables.tf
  terraform/output.tf
  terraform/variables.tf
Labels: enhancement

#32 Fix WebSocket timeout
  websockets/broker.go
  websockets/client.go
  websockets/conversation.go
Labels: bug

#33 Fix issue with Sync for a non-existent checkpoint
  websockets/conversation.go
Labels: bug
